-- ============================================================
-- INVENTORY MANAGEMENT SYSTEM - COMPLETE DATABASE SCHEMA
-- Target: PostgreSQL (Neon)
-- Created: 2026-08-23
-- Tables: 9 (based on actual JPA entities)
-- ============================================================

-- No extensions required by the application.
-- No functions, triggers, or views required.
-- All business logic is handled in Java (Spring Boot).

-- ============================================================
-- 1. USERS
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    email VARCHAR(255),
    role VARCHAR(255) DEFAULT 'User',
    status VARCHAR(255) DEFAULT 'Active',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ============================================================
-- 2. CUSTOMERS
-- ============================================================
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(255) NOT NULL UNIQUE,
    customer_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    address TEXT,
    status VARCHAR(255) DEFAULT 'Active',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ============================================================
-- 3. SUPPLIERS
-- ============================================================
CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id VARCHAR(255) NOT NULL UNIQUE,
    supplier_name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    address TEXT,
    status VARCHAR(255) DEFAULT 'Active',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ============================================================
-- 4. ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(255) NOT NULL UNIQUE,
    item_name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    unit VARCHAR(255) NOT NULL,
    price NUMERIC(19,2) NOT NULL,
    stock_qty INTEGER NOT NULL DEFAULT 0,
    reorder_level INTEGER NOT NULL DEFAULT 5,
    status VARCHAR(255) DEFAULT 'In Stock',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ============================================================
-- 5. PURCHASES
-- ============================================================
CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_no VARCHAR(255) NOT NULL UNIQUE,
    supplier_id BIGINT,
    purchase_date DATE NOT NULL,
    payment_type VARCHAR(255) DEFAULT 'Cash',
    subtotal NUMERIC(19,2) NOT NULL DEFAULT 0,
    discount NUMERIC(19,2) NOT NULL DEFAULT 0,
    tax_rate NUMERIC(19,2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    amount_paid NUMERIC(19,2) NOT NULL DEFAULT 0,
    balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    purchase_person VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ============================================================
-- 6. PURCHASE_ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL,
    item_id BIGINT,
    item_code VARCHAR(255) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    unit_price NUMERIC(19,2) NOT NULL,
    quantity INTEGER NOT NULL,
    discount_percent NUMERIC(19,2) DEFAULT 0,
    amount NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP
);

-- ============================================================
-- 7. SALES
-- ============================================================
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(255) NOT NULL UNIQUE,
    customer_id BIGINT,
    invoice_date DATE NOT NULL,
    payment_type VARCHAR(255) DEFAULT 'Cash',
    subtotal NUMERIC(19,2) NOT NULL DEFAULT 0,
    discount NUMERIC(19,2) NOT NULL DEFAULT 0,
    tax_rate NUMERIC(19,2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    amount_paid NUMERIC(19,2) NOT NULL DEFAULT 0,
    balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    sales_person VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ============================================================
-- 8. SALE_ITEMS
-- ============================================================
CREATE TABLE IF NOT EXISTS sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    item_id BIGINT,
    item_code VARCHAR(255) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    unit_price NUMERIC(19,2) NOT NULL,
    quantity INTEGER NOT NULL,
    discount_percent NUMERIC(19,2) DEFAULT 0,
    amount NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP
);

-- ============================================================
-- 9. STOCK_REPORTS
-- ============================================================
CREATE TABLE IF NOT EXISTS stock_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    reorder_level INTEGER,
    status VARCHAR(255)
);
